Business logic layer's datamodel integrateion (logic side) resolves #13
VSZM/Dixit_By_MonkeyzWithKeyboardz_ELTE pull request #18
Opened 2016-10-18 14:30 UTC by matyimat

2016-10-18 20:22 UTC, VSZM reviewed
Please fix these

2016-10-18 20:22 UTC, VSZM commented on Dixit_Logic/Interfaces/IDixitGame.cs
>          int AddPlayer(String name);
How about instead of returning a simple int, return an IPlayer here?

2016-10-18 20:22 UTC, VSZM commented on Dixit_Logic/Interfaces/IDixitGame.cs
>          int AddPlayer(String name);
Also in the PutCard method.. It is not an int that is putting the card, but a Player. Makes the code more readable.

2016-10-18 20:45 UTC, matyimat commented on Dixit_Logic/Interfaces/IDixitGame.cs
>          int AddPlayer(String name);
I ll correct these mistakes after Marci ll resolve conflicts in his pull request to avoid more conflicts.

2016-10-18 21:01 UTC, VSZM commented on Dixit_Logic/Interfaces/IDixitGame.cs
>          int AddPlayer(String name);
I think you can go ahead, you will not conflict.

2016-10-20 07:53 UTC, SilverGeri commented on Dixit_Logic/Interfaces/IGameState.cs
> +    interface IGameState
please make interfaces public

2016-10-23 17:50 UTC, VSZM requested changes

2016-10-23 17:50 UTC, VSZM commented on Dixit_Logic/Interfaces/IDeck.cs
> +        IList<ICard> Cards
public

2016-10-23 17:50 UTC, VSZM commented on Dixit_Logic/Interfaces/IDeck.cs
>      interface IDeck
public

2016-10-23 17:50 UTC, VSZM commented on Dixit_Logic/Interfaces/IDeck.cs
> +        void AddCards(IList<ICard> cards);
public...

2016-10-23 17:50 UTC, VSZM commented on Dixit_Logic/Interfaces/IDixitGame.cs
>      interface IDixitGame
public!

2016-10-23 17:50 UTC, VSZM commented on Dixit_Logic/Interfaces/IDixitGame.cs
> +        void EvaluatePoints();
public

2016-10-24 13:46 UTC, VSZM commented
Matyi in the latest commit you still have not made the interfaces public. Please make all of the interfaces public so I can approve.

2016-10-24 14:01 UTC, VSZM approved these changes

2016-10-24 14:01 UTC, merged