Implement those classes that are needed for starting a new game and adding players (resolves #23)
VSZM/Dixit_By_MonkeyzWithKeyboardz_ELTE pull request #27
Opened 2016-11-03 16:25 UTC by matyimat

I don't implement fully this classes, only the necessary parts which have needed to resolve this task. (#23)

2016-11-05 21:45 UTC, VSZM requested changes

2016-11-05 21:45 UTC, VSZM commented on Dixit_Logic/Classes/GameState.cs
> +        private IPlayer _actPlayer;
suggestion: change the variable name to storyTeller

2016-11-05 21:45 UTC, VSZM commented on Dixit_Logic/Classes/GameState.cs
> +        private string _cardAssocText;
This could be called storyText or simply story

2016-11-05 21:45 UTC, VSZM commented on Dixit_Logic/Classes/GameState.cs
> +        private Dictionary<IPlayer, int> _points;
I think this could even go to the IPlayer.

2016-11-05 21:45 UTC, VSZM commented on Dixit_Logic/Classes/Player.cs
> +            return (_id == p._id) && (_name == p._name);
Since ids are unique, Comparing the ID would be enough.

2016-11-05 21:45 UTC, VSZM commented on Dixit_Logic/Classes/Player.cs
> +            return _id.GetHashCode() ^ _name.GetHashCode();
Again, just base hashcode on ID. KISS

2016-11-07 12:30 UTC, matyimat commented on Dixit_Logic/Classes/GameState.cs
> +        private Dictionary<IPlayer, int> _points;
Yes it could , i did it too. But Marci told me that it will be better in practice.

2016-11-07 12:36 UTC, VSZM commented on Dixit_Logic/Classes/GameState.cs
> +        private Dictionary<IPlayer, int> _points;
Okay, fine by me. Focus on the other points pls.

2016-11-07 13:51 UTC, VSZM approved these changes

2016-11-07 13:51 UTC, merged