Implement ICard and IDeck interfaces
VSZM/Dixit_By_MonkeyzWithKeyboardz_ELTE pull request #45
Opened 2016-11-20 11:43 UTC by matyimat

in addition i added BaseCards to the GameState for Marci

2016-11-20 19:40 UTC, SilverGeri commented on Dixit_Logic/Classes/Card.cs
> +        Bitmap _image;
There is no use having this field anymore, Bitmap cannot be used as source, we need an IValueConverter for that, but I already implemented one that can make ImageSource from an ID in https://github.com/VSZM/Dixit_By_MonkeyzWithKeyboardz_ELTE/pull/42

It is unnecessary to contain the images in Dixit_Logic when id is enough

2016-11-20 21:52 UTC, matyimat commented on Dixit_Logic/Classes/Card.cs
> +        Bitmap _image;
ok, I'm going to correct this tomorrow

2016-11-21 01:50 UTC, VSZM requested changes

2016-11-21 01:50 UTC, VSZM commented on Dixit_Logic/Classes/Deck.cs
> +            foreach (ICard card in cards)
Use List.AddRange  method here. 
https://msdn.microsoft.com/en-us/library/z883w3dc(v=vs.110).aspx

2016-11-21 01:50 UTC, VSZM commented on Dixit_Logic/Classes/Deck.cs
> +            foreach (ICard card in cards)
https://msdn.microsoft.com/en-us/library/z883w3dc(v=vs.110).aspx

2016-11-21 01:50 UTC, VSZM commented on Dixit_Logic/Classes/Hand.cs
> +            foreach (ICard card in cards)
http://stackoverflow.com/questions/3173320/text-progress-bar-in-the-console

2016-11-21 01:50 UTC, VSZM commented on Dixit_Logic/Classes/Hand.cs
> +        public void AddCards(IList<ICard> cards)
I think there should be a method which adds a Single ICard. In each turn the player plays a Card, and then Draws a single one. With this method only you will have to wrap these single values into Lists.

2016-11-21 11:48 UTC, matyimat commented on Dixit_Logic/Classes/Hand.cs
> +            foreach (ICard card in cards)
I suppose you wanted to signify the same problem as previous two : https://msdn.microsoft.com/en-us/library/z883w3dc(v=vs.110).aspx

2016-11-21 11:52 UTC, matyimat commented on Dixit_Logic/Classes/Hand.cs
> +        public void AddCards(IList<ICard> cards)
It is also true. I ll add an AddCard method

2016-11-21 14:12 UTC, VSZM commented on Dixit_Logic/Classes/Hand.cs
> +            foreach (ICard card in cards)
Yes, I mixed up a link with another one on my clipboard : )

2016-11-21 14:12 UTC, VSZM approved these changes

2016-11-21 14:13 UTC, merged