Implement PutCard method
VSZM/Dixit_By_MonkeyzWithKeyboardz_ELTE pull request #50
Opened 2016-11-29 15:45 UTC by matyimat

2016-11-30 00:02 UTC, VSZM requested changes

2016-11-30 00:02 UTC, VSZM commented on Dixit_Logic/Classes/DixitGame.cs
> +                    _actGameState.RoundStatus = PhaseStatus.AssociationTelling;// ha még nem indított már el valaki korábban
How do we know who is exactly the story teller?

2016-11-30 00:02 UTC, VSZM commented on Dixit_Logic/Classes/DixitGame.cs
> +            if(_actGameState.RoundStatus == PhaseStatus.AssociationTelling)
I think in this if clause we need to check if the player in the parameter is equal to the player who we are expecting to hear the story from.

2016-11-30 00:02 UTC, VSZM commented on Dixit_Logic/Classes/DixitGame.cs
> +                _actGameState.ActualPlayer = player;
Actual player should already be known here.

2016-11-30 00:02 UTC, VSZM commented on Dixit_Logic/Classes/DixitGame.cs
> +                        _actGameState.BoardDeck.AddCard(selectedCard);
During point calculations at the end of round, how will we know the relation between the cards on the board, and the players that put them down?

2016-11-30 00:02 UTC, VSZM commented on Dixit_Logic/Classes/GameState.cs
> +    public enum PhaseStatus { BeforeStart = 0, AssociationTelling = 1, Putting = 2, Guessing = 3, RoundEnd = 4 };
Don't we need a Phase here for signaling the game is over?

2016-12-02 15:55 UTC, matyimat commented on Dixit_Logic/Classes/DixitGame.cs
> +                        _actGameState.BoardDeck.AddCard(selectedCard);
I will add a player information to the cards what will indicate the player who drawed them.

2016-12-04 12:39 UTC, VSZM approved these changes

2016-12-04 12:39 UTC, merged