Fully Implement Game Logic
VSZM/Dixit_By_MonkeyzWithKeyboardz_ELTE pull request #57
Opened 2016-12-05 15:27 UTC by matyimat

Without testing

2016-12-05 15:49 UTC, VSZM requested changes
Please fix the requested changes

2016-12-05 15:49 UTC, VSZM commented on Dixit_Logic/Classes/DixitGame.cs
> +        /// This event is triggered when all cards are consumed from the MainDeck and players have no more cards too .
If this comment is true, then the implementation is wrong. A Dixit game lasts until one of the players reach 30 points. Playing until all cards are gone is not a reliable metric as the number of cards can be vast.

2016-12-05 15:49 UTC, VSZM commented on Dixit_Logic/Classes/GameState.cs
> +            //add cards to main deck
@matyimat How do you know the number of cards? This should not be hardcoded, as this part of the code is not responsible for the data. Data layer provides an interface for getting back the list of cards.

2016-12-06 12:27 UTC, SilverGeri commented on Dixit_Logic/Classes/DixitGame.cs
> +                        originalCard = (Card)boardCard;
you can add a `break` here

2016-12-06 12:31 UTC, SilverGeri commented on Dixit_Logic/Classes/DixitGame.cs
> +
you could just do `actPlayerIndex = (actPlayerIndex +1)%Players.Count`

2016-12-06 12:32 UTC, SilverGeri commented on Dixit_Logic/Classes/DixitGame.cs
> +                    NewRound(this, new EventArgs());
@selleim please don't forget to handle this action. (I know this comment doesn't really belong here, but the deadline is near)

2016-12-06 12:37 UTC, SilverGeri commented on Dixit_Logic/Interfaces/IGameState.cs
> +        int ObtainablePoint
where can you reset it? I saw you hardcoded 5 in GameState.cs but if we want to play with another obtainable point, do we have to rebuild the project? I think this property should be public

2016-12-06 13:33 UTC, matyimat commented on Dixit_Logic/Interfaces/IGameState.cs
> +        int ObtainablePoint
This is public, i cant add acces modifier here, only in the class what implement the interface (GameState)

2016-12-06 15:13 UTC, VSZM approved these changes

2016-12-06 15:13 UTC, merged